/**
 * Promotion report generator.
 * Produces a markdown report summarizing readiness state.
 */

import { writeFileSync } from "node:fs";
import type { PromotionResult, CoverageStats, EvalSummary, HealthSummary, FixtureStatus } from "./criteria.js";

export interface ReportData {
  promotion: PromotionResult;
  evalSummary: EvalSummary;
  healthSummary: HealthSummary;
  coverage: CoverageStats;
  fixtures: FixtureStatus;
  configPath: string;
  generatedAt: string;
}

export function generateReport(data: ReportData): string {
  const { promotion, evalSummary, healthSummary, coverage, fixtures, configPath, generatedAt } = data;

  const lines: string[] = [];

  // Header
  lines.push(`# Promotion Report`);
  lines.push('');
  lines.push(`**Generated:** ${generatedAt}`);
  lines.push(`**Config:** ${configPath}`);
  lines.push(`**Promotion Level:** ${promotion.level} — ${promotion.level_name}`);
  lines.push('');

  // Level explanation
  lines.push('---');
  lines.push('');
  lines.push('## Promotion Level');
  lines.push('');
  lines.push(`| Level | Status |`);
  lines.push(`|---|---|`);
  lines.push(`| L0: Not Ready | ${promotion.level === 'L0' ? '← CURRENT' : '✓ Passed'} |`);
  lines.push(`| L1: Ready with Conditions | ${promotion.level === 'L1' ? '← CURRENT' : promotion.level === 'L0' ? '—' : '✓ Passed'} |`);
  lines.push(`| L2: Ready for Internal Deployment | ${promotion.level === 'L2' ? '← CURRENT' : ['L0', 'L1'].includes(promotion.level) ? '—' : '✓ Passed'} |`);
  lines.push(`| L3: Ready for Production Agents | ${promotion.level === 'L3' ? '← CURRENT' : '—'} |`);
  lines.push('');

  // Criteria
  lines.push('## Criteria');
  lines.push('');
  lines.push('| Criterion | Met | Detail |');
  lines.push('|---|---|---|');
  for (const c of promotion.criteria) {
    lines.push(`| ${c.criterion} | ${c.met ? '✓' : '✗'} | ${c.detail} |`);
  }
  lines.push('');

  // Blockers
  if (promotion.blockers.length > 0) {
    lines.push('## Blockers');
    lines.push('');
    for (const b of promotion.blockers) {
      lines.push(`- ${b}`);
    }
    lines.push('');
  }

  // Conditions
  if (promotion.conditions.length > 0) {
    lines.push('## Conditions (keeping at L1)');
    lines.push('');
    for (const c of promotion.conditions) {
      lines.push(`- ${c}`);
    }
    lines.push('');
  }

  // Eval Summary
  lines.push('---');
  lines.push('');
  lines.push('## Eval Summary');
  lines.push('');
  lines.push(`| Track | Pass | Total |`);
  lines.push(`|---|---|---|`);
  lines.push(`| Track A (SQL correctness) | ${evalSummary.track_a_pass} | ${evalSummary.track_a_total} |`);
  lines.push(`| Track B (Knowledge retrieval) | ${evalSummary.track_b_pass} | ${evalSummary.track_b_total} |`);
  lines.push(`| Track C (Workflow) | ${evalSummary.track_c_pass} | ${evalSummary.track_c_total} |`);
  lines.push(`| Negative controls | ${evalSummary.negative_pass} | ${evalSummary.negative_total} |`);
  lines.push(`| **Total** | **${evalSummary.pass}** | **${evalSummary.total}** |`);
  lines.push('');

  // Health Check
  lines.push('## Health Check');
  lines.push('');
  lines.push(`- Connection errors: ${healthSummary.connection_errors}`);
  lines.push(`- Config issues: ${healthSummary.config_issues}`);
  lines.push(`- Unannotated fields: ${healthSummary.unannotated_fields}`);
  lines.push(`- Stale annotations: ${healthSummary.stale_annotations}`);
  lines.push('');

  // Coverage
  lines.push('## Config Coverage');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Field annotation coverage | ${coverage.coverage_pct}% (${coverage.annotated_fields}/${coverage.total_live_fields}) |`);
  lines.push(`| Views annotated | ${coverage.view_count} |`);
  lines.push(`| Rules defined | ${coverage.rule_count} |`);
  lines.push(`| Terms defined | ${coverage.term_count} |`);
  lines.push(`| Metrics defined | ${coverage.metric_count} |`);
  lines.push('');

  // Fixtures
  lines.push('## Fixture Status');
  lines.push('');
  lines.push(`- True-north fixtures: ${fixtures.true_north_exists ? `${fixtures.true_north_count} fixture(s)` : 'None'}`);
  lines.push(`- Golden result fixtures: ${fixtures.golden_exists ? `${fixtures.golden_count} fixture(s)` : 'None'}`);
  lines.push(`- Online verification: ${fixtures.online_verified ? 'Passed' : 'Not verified'}`);
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by schema-context-mcp promote*');
  lines.push('');

  return lines.join('\n');
}

export function writeReport(report: string, outputPath: string): void {
  writeFileSync(outputPath, report, 'utf-8');
}
